name_label_dict ={
    'this_ely': 'Elektrolyseur',
    'this_pem_ely': 'PEM-Elektrolyseur',
    'pv_output': 'PV-Anlage',
    'solar_output': 'PV-Anlage',
    'wind_output': 'WE-Anlage',
    'th_demand': 'Heizbedarf',
    'h2_demand': 'Wasserstoffbedarf',
    'h2_compressor': 'Wasserstoffkompressor (higher pressure)',
    'from_grid': 'Strombezug',
    'to_grid': 'Stromeinspeisung',
    'h2_storage': 'Wasserstoffspeicher',
    'fuel_cell_chp': 'Brennstoffzelle',
    'CHP_Methane': 'Biogas-BHKW',
    'ch4_grid': 'Biogas-Zufuhr',
    'h2_compressor_from_ely': 'Wasserstoffkompressor (lower pressure)',
    'dummy_2': 'Gebrauchte PV-Elektrizität',
    'dummy_1': 'Gebrauchte Wind-Elektrizität',
    'pv_to_grid': 'Überschüssige PV-Elektrizität',
    'wind_to_grid': 'Überschüssige Wind-Elektrizität',
}
